SERVER_IP_ADDR="127.0.0.1"
SERVER_PORT=54781

MAX_BUFFER_SIZE_IN_BYTES=1024

# ENCRYPTION and DECRYPTION CONTSTANTS
AES_BLOCK_SIZE_BITS=128
AES_BLOCK_SIZE_BYTES=AES_BLOCK_SIZE_BITS // 8

# Message handling constants
MAX_RETRIES=3
DEFAULT_TIMEOUT_IN_SEC=1
EXPONENTIAL_BACKOFF=2
RETRY_DELAY_IN_SEC=1

SERVER_PUBLIC_KEY="-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoIo2pjzkWBCm19TqmFE/\nIiVgveMt4TQe/WC3hGi/ohHisH6lytVOOET5/3wCx0ndbxpmJQKqAzYqZeNRnfo5\nGZVRGh4jWYi/PYSRhcqbwVcRj8FnQ6JU/b5wExtXFO9SJQPALBAwAQGYrwIWrU+6\nZ8Y1pDwWxY1NjVui/Tl1A9ribi8BU4Fy2VKJ+GsMkv8u244i01m2Igep73keG+SV\nR5LfS6mFVDlL/ZWR2DIBivGM8WianxcYo/OJ9nxV3LGHsQ6o2hOCtFu3ACYMbWX2\nvSwwtAdkZzVHBjSa6XhHi9hgz2kZx++ApGEPwnYAGWVs/gA61QxxNyirVWldwEzI\njQIDAQAB\n-----END PUBLIC KEY-----"

# Different commands that can be issued to the server
START_SESSION="START_SESSION"

# SERVER RESPONSES
SUCCESS="SUCCESS"
FAILURE="FAILURE"

## START_SESSION
START_SESSION_SUCCESS="START_SESSION_SUCCESS"
START_SESSION_FAILURE="START_SESSION_FAILURE"